name: Waf Legacy Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  waf:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, docker, builder]
    name: Docker Waf
    container:
      image: ghcr.io/steinwurf/waf:latest
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests -vv
